// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: finality_gadget.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FinalityGadgetClient is the client API for FinalityGadget service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinalityGadgetClient interface {
	QueryIsBlockBabylonFinalized(ctx context.Context, in *QueryIsBlockBabylonFinalizedRequest, opts ...grpc.CallOption) (*QueryIsBlockBabylonFinalizedResponse, error)
	QueryBlockRangeBabylonFinalized(ctx context.Context, in *QueryBlockRangeBabylonFinalizedRequest, opts ...grpc.CallOption) (*QueryBlockRangeBabylonFinalizedResponse, error)
	QueryEarliestDelHeight(ctx context.Context, in *QueryEarliestDelHeightRequest, opts ...grpc.CallOption) (*QueryEarliestDelHeightResponse, error)
}

type finalityGadgetClient struct {
	cc grpc.ClientConnInterface
}

func NewFinalityGadgetClient(cc grpc.ClientConnInterface) FinalityGadgetClient {
	return &finalityGadgetClient{cc}
}

func (c *finalityGadgetClient) QueryIsBlockBabylonFinalized(ctx context.Context, in *QueryIsBlockBabylonFinalizedRequest, opts ...grpc.CallOption) (*QueryIsBlockBabylonFinalizedResponse, error) {
	out := new(QueryIsBlockBabylonFinalizedResponse)
	err := c.cc.Invoke(ctx, "/proto.FinalityGadget/QueryIsBlockBabylonFinalized", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finalityGadgetClient) QueryBlockRangeBabylonFinalized(ctx context.Context, in *QueryBlockRangeBabylonFinalizedRequest, opts ...grpc.CallOption) (*QueryBlockRangeBabylonFinalizedResponse, error) {
	out := new(QueryBlockRangeBabylonFinalizedResponse)
	err := c.cc.Invoke(ctx, "/proto.FinalityGadget/QueryBlockRangeBabylonFinalized", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finalityGadgetClient) QueryEarliestDelHeight(ctx context.Context, in *QueryEarliestDelHeightRequest, opts ...grpc.CallOption) (*QueryEarliestDelHeightResponse, error) {
	out := new(QueryEarliestDelHeightResponse)
	err := c.cc.Invoke(ctx, "/proto.FinalityGadget/QueryEarliestDelHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinalityGadgetServer is the server API for FinalityGadget service.
// All implementations must embed UnimplementedFinalityGadgetServer
// for forward compatibility
type FinalityGadgetServer interface {
	QueryIsBlockBabylonFinalized(context.Context, *QueryIsBlockBabylonFinalizedRequest) (*QueryIsBlockBabylonFinalizedResponse, error)
	QueryBlockRangeBabylonFinalized(context.Context, *QueryBlockRangeBabylonFinalizedRequest) (*QueryBlockRangeBabylonFinalizedResponse, error)
	QueryEarliestDelHeight(context.Context, *QueryEarliestDelHeightRequest) (*QueryEarliestDelHeightResponse, error)
	mustEmbedUnimplementedFinalityGadgetServer()
}

// UnimplementedFinalityGadgetServer must be embedded to have forward compatible implementations.
type UnimplementedFinalityGadgetServer struct {
}

func (UnimplementedFinalityGadgetServer) QueryIsBlockBabylonFinalized(context.Context, *QueryIsBlockBabylonFinalizedRequest) (*QueryIsBlockBabylonFinalizedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryIsBlockBabylonFinalized not implemented")
}
func (UnimplementedFinalityGadgetServer) QueryBlockRangeBabylonFinalized(context.Context, *QueryBlockRangeBabylonFinalizedRequest) (*QueryBlockRangeBabylonFinalizedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBlockRangeBabylonFinalized not implemented")
}
func (UnimplementedFinalityGadgetServer) QueryEarliestDelHeight(context.Context, *QueryEarliestDelHeightRequest) (*QueryEarliestDelHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryEarliestDelHeight not implemented")
}
func (UnimplementedFinalityGadgetServer) mustEmbedUnimplementedFinalityGadgetServer() {}

// UnsafeFinalityGadgetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinalityGadgetServer will
// result in compilation errors.
type UnsafeFinalityGadgetServer interface {
	mustEmbedUnimplementedFinalityGadgetServer()
}

func RegisterFinalityGadgetServer(s grpc.ServiceRegistrar, srv FinalityGadgetServer) {
	s.RegisterService(&FinalityGadget_ServiceDesc, srv)
}

func _FinalityGadget_QueryIsBlockBabylonFinalized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryIsBlockBabylonFinalizedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinalityGadgetServer).QueryIsBlockBabylonFinalized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FinalityGadget/QueryIsBlockBabylonFinalized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinalityGadgetServer).QueryIsBlockBabylonFinalized(ctx, req.(*QueryIsBlockBabylonFinalizedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinalityGadget_QueryBlockRangeBabylonFinalized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBlockRangeBabylonFinalizedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinalityGadgetServer).QueryBlockRangeBabylonFinalized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FinalityGadget/QueryBlockRangeBabylonFinalized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinalityGadgetServer).QueryBlockRangeBabylonFinalized(ctx, req.(*QueryBlockRangeBabylonFinalizedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinalityGadget_QueryEarliestDelHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryEarliestDelHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinalityGadgetServer).QueryEarliestDelHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.FinalityGadget/QueryEarliestDelHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinalityGadgetServer).QueryEarliestDelHeight(ctx, req.(*QueryEarliestDelHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinalityGadget_ServiceDesc is the grpc.ServiceDesc for FinalityGadget service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinalityGadget_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.FinalityGadget",
	HandlerType: (*FinalityGadgetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryIsBlockBabylonFinalized",
			Handler:    _FinalityGadget_QueryIsBlockBabylonFinalized_Handler,
		},
		{
			MethodName: "QueryBlockRangeBabylonFinalized",
			Handler:    _FinalityGadget_QueryBlockRangeBabylonFinalized_Handler,
		},
		{
			MethodName: "QueryEarliestDelHeight",
			Handler:    _FinalityGadget_QueryEarliestDelHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "finality_gadget.proto",
}
