// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: finality_gadget.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type L2Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHash      string `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockHeight    uint64 `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	BlockTimestamp uint64 `protobuf:"varint,3,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
}

func (x *L2Block) Reset() {
	*x = L2Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finality_gadget_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L2Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2Block) ProtoMessage() {}

func (x *L2Block) ProtoReflect() protoreflect.Message {
	mi := &file_finality_gadget_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2Block.ProtoReflect.Descriptor instead.
func (*L2Block) Descriptor() ([]byte, []int) {
	return file_finality_gadget_proto_rawDescGZIP(), []int{0}
}

func (x *L2Block) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *L2Block) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *L2Block) GetBlockTimestamp() uint64 {
	if x != nil {
		return x.BlockTimestamp
	}
	return 0
}

type QueryIsBlockBabylonFinalizedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	L2Block *L2Block `protobuf:"bytes,1,opt,name=l2_block,json=l2Block,proto3" json:"l2_block,omitempty"`
}

func (x *QueryIsBlockBabylonFinalizedRequest) Reset() {
	*x = QueryIsBlockBabylonFinalizedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finality_gadget_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryIsBlockBabylonFinalizedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIsBlockBabylonFinalizedRequest) ProtoMessage() {}

func (x *QueryIsBlockBabylonFinalizedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finality_gadget_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIsBlockBabylonFinalizedRequest.ProtoReflect.Descriptor instead.
func (*QueryIsBlockBabylonFinalizedRequest) Descriptor() ([]byte, []int) {
	return file_finality_gadget_proto_rawDescGZIP(), []int{1}
}

func (x *QueryIsBlockBabylonFinalizedRequest) GetL2Block() *L2Block {
	if x != nil {
		return x.L2Block
	}
	return nil
}

type QueryIsBlockBabylonFinalizedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BabylonFinalized bool `protobuf:"varint,1,opt,name=babylon_finalized,json=babylonFinalized,proto3" json:"babylon_finalized,omitempty"`
}

func (x *QueryIsBlockBabylonFinalizedResponse) Reset() {
	*x = QueryIsBlockBabylonFinalizedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finality_gadget_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryIsBlockBabylonFinalizedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryIsBlockBabylonFinalizedResponse) ProtoMessage() {}

func (x *QueryIsBlockBabylonFinalizedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finality_gadget_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryIsBlockBabylonFinalizedResponse.ProtoReflect.Descriptor instead.
func (*QueryIsBlockBabylonFinalizedResponse) Descriptor() ([]byte, []int) {
	return file_finality_gadget_proto_rawDescGZIP(), []int{2}
}

func (x *QueryIsBlockBabylonFinalizedResponse) GetBabylonFinalized() bool {
	if x != nil {
		return x.BabylonFinalized
	}
	return false
}

type QueryBlockRangeBabylonFinalizedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	L2Block []*L2Block `protobuf:"bytes,1,rep,name=l2_block,json=l2Block,proto3" json:"l2_block,omitempty"`
}

func (x *QueryBlockRangeBabylonFinalizedRequest) Reset() {
	*x = QueryBlockRangeBabylonFinalizedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finality_gadget_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryBlockRangeBabylonFinalizedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBlockRangeBabylonFinalizedRequest) ProtoMessage() {}

func (x *QueryBlockRangeBabylonFinalizedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finality_gadget_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBlockRangeBabylonFinalizedRequest.ProtoReflect.Descriptor instead.
func (*QueryBlockRangeBabylonFinalizedRequest) Descriptor() ([]byte, []int) {
	return file_finality_gadget_proto_rawDescGZIP(), []int{3}
}

func (x *QueryBlockRangeBabylonFinalizedRequest) GetL2Block() []*L2Block {
	if x != nil {
		return x.L2Block
	}
	return nil
}

type QueryBlockRangeBabylonFinalizedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastFinalizedHeight uint64 `protobuf:"varint,1,opt,name=last_finalized_height,json=lastFinalizedHeight,proto3" json:"last_finalized_height,omitempty"`
}

func (x *QueryBlockRangeBabylonFinalizedResponse) Reset() {
	*x = QueryBlockRangeBabylonFinalizedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finality_gadget_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryBlockRangeBabylonFinalizedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBlockRangeBabylonFinalizedResponse) ProtoMessage() {}

func (x *QueryBlockRangeBabylonFinalizedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finality_gadget_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBlockRangeBabylonFinalizedResponse.ProtoReflect.Descriptor instead.
func (*QueryBlockRangeBabylonFinalizedResponse) Descriptor() ([]byte, []int) {
	return file_finality_gadget_proto_rawDescGZIP(), []int{4}
}

func (x *QueryBlockRangeBabylonFinalizedResponse) GetLastFinalizedHeight() uint64 {
	if x != nil {
		return x.LastFinalizedHeight
	}
	return 0
}

type QueryEarliestDelHeightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueryEarliestDelHeightRequest) Reset() {
	*x = QueryEarliestDelHeightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finality_gadget_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryEarliestDelHeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEarliestDelHeightRequest) ProtoMessage() {}

func (x *QueryEarliestDelHeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finality_gadget_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEarliestDelHeightRequest.ProtoReflect.Descriptor instead.
func (*QueryEarliestDelHeightRequest) Descriptor() ([]byte, []int) {
	return file_finality_gadget_proto_rawDescGZIP(), []int{5}
}

type QueryEarliestDelHeightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstDelHeight uint64 `protobuf:"varint,1,opt,name=first_del_height,json=firstDelHeight,proto3" json:"first_del_height,omitempty"`
}

func (x *QueryEarliestDelHeightResponse) Reset() {
	*x = QueryEarliestDelHeightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_finality_gadget_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryEarliestDelHeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEarliestDelHeightResponse) ProtoMessage() {}

func (x *QueryEarliestDelHeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finality_gadget_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEarliestDelHeightResponse.ProtoReflect.Descriptor instead.
func (*QueryEarliestDelHeightResponse) Descriptor() ([]byte, []int) {
	return file_finality_gadget_proto_rawDescGZIP(), []int{6}
}

func (x *QueryEarliestDelHeightResponse) GetFirstDelHeight() uint64 {
	if x != nil {
		return x.FirstDelHeight
	}
	return 0
}

var File_finality_gadget_proto protoreflect.FileDescriptor

var file_finality_gadget_proto_rawDesc = []byte{
	0x0a, 0x15, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x67, 0x61, 0x64, 0x67, 0x65,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x74,
	0x0a, 0x07, 0x4c, 0x32, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x22, 0x50, 0x0a, 0x23, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x08, 0x6c,
	0x32, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x32, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x07, 0x6c,
	0x32, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x53, 0x0a, 0x24, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49,
	0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x46, 0x69, 0x6e,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b,
	0x0a, 0x11, 0x62, 0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x5f, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x62, 0x61, 0x62, 0x79, 0x6c,
	0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x22, 0x53, 0x0a, 0x26, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x61,
	0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x08, 0x6c, 0x32, 0x5f, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4c, 0x32, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x07, 0x6c, 0x32, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x22, 0x5d, 0x0a, 0x27, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x42, 0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x5f, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x13, 0x6c, 0x61, 0x73, 0x74,
	0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22,
	0x1f, 0x0a, 0x1d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x61, 0x72, 0x6c, 0x69, 0x65, 0x73, 0x74,
	0x44, 0x65, 0x6c, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x4a, 0x0a, 0x1e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x61, 0x72, 0x6c, 0x69, 0x65, 0x73,
	0x74, 0x44, 0x65, 0x6c, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x64, 0x65, 0x6c, 0x5f,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x32, 0xf3, 0x02, 0x0a,
	0x0e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x47, 0x61, 0x64, 0x67, 0x65, 0x74, 0x12,
	0x77, 0x0a, 0x1c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x42,
	0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x12,
	0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x42, 0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x80, 0x01, 0x0a, 0x1f, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x61, 0x62, 0x79,
	0x6c, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x12, 0x2d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x42, 0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x42, 0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65, 0x0a, 0x16, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x45, 0x61, 0x72, 0x6c, 0x69, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x48,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x45, 0x61, 0x72, 0x6c, 0x69, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x48, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x61, 0x72, 0x6c, 0x69, 0x65, 0x73,
	0x74, 0x44, 0x65, 0x6c, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x62, 0x61, 0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x62, 0x61,
	0x62, 0x79, 0x6c, 0x6f, 0x6e, 0x2d, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x2d, 0x67,
	0x61, 0x64, 0x67, 0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_finality_gadget_proto_rawDescOnce sync.Once
	file_finality_gadget_proto_rawDescData = file_finality_gadget_proto_rawDesc
)

func file_finality_gadget_proto_rawDescGZIP() []byte {
	file_finality_gadget_proto_rawDescOnce.Do(func() {
		file_finality_gadget_proto_rawDescData = protoimpl.X.CompressGZIP(file_finality_gadget_proto_rawDescData)
	})
	return file_finality_gadget_proto_rawDescData
}

var file_finality_gadget_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_finality_gadget_proto_goTypes = []interface{}{
	(*L2Block)(nil), // 0: proto.L2Block
	(*QueryIsBlockBabylonFinalizedRequest)(nil),     // 1: proto.QueryIsBlockBabylonFinalizedRequest
	(*QueryIsBlockBabylonFinalizedResponse)(nil),    // 2: proto.QueryIsBlockBabylonFinalizedResponse
	(*QueryBlockRangeBabylonFinalizedRequest)(nil),  // 3: proto.QueryBlockRangeBabylonFinalizedRequest
	(*QueryBlockRangeBabylonFinalizedResponse)(nil), // 4: proto.QueryBlockRangeBabylonFinalizedResponse
	(*QueryEarliestDelHeightRequest)(nil),           // 5: proto.QueryEarliestDelHeightRequest
	(*QueryEarliestDelHeightResponse)(nil),          // 6: proto.QueryEarliestDelHeightResponse
}
var file_finality_gadget_proto_depIdxs = []int32{
	0, // 0: proto.QueryIsBlockBabylonFinalizedRequest.l2_block:type_name -> proto.L2Block
	0, // 1: proto.QueryBlockRangeBabylonFinalizedRequest.l2_block:type_name -> proto.L2Block
	1, // 2: proto.FinalityGadget.QueryIsBlockBabylonFinalized:input_type -> proto.QueryIsBlockBabylonFinalizedRequest
	3, // 3: proto.FinalityGadget.QueryBlockRangeBabylonFinalized:input_type -> proto.QueryBlockRangeBabylonFinalizedRequest
	5, // 4: proto.FinalityGadget.QueryEarliestDelHeight:input_type -> proto.QueryEarliestDelHeightRequest
	2, // 5: proto.FinalityGadget.QueryIsBlockBabylonFinalized:output_type -> proto.QueryIsBlockBabylonFinalizedResponse
	4, // 6: proto.FinalityGadget.QueryBlockRangeBabylonFinalized:output_type -> proto.QueryBlockRangeBabylonFinalizedResponse
	6, // 7: proto.FinalityGadget.QueryEarliestDelHeight:output_type -> proto.QueryEarliestDelHeightResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_finality_gadget_proto_init() }
func file_finality_gadget_proto_init() {
	if File_finality_gadget_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_finality_gadget_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L2Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finality_gadget_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryIsBlockBabylonFinalizedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finality_gadget_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryIsBlockBabylonFinalizedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finality_gadget_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryBlockRangeBabylonFinalizedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finality_gadget_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryBlockRangeBabylonFinalizedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finality_gadget_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryEarliestDelHeightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_finality_gadget_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryEarliestDelHeightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_finality_gadget_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finality_gadget_proto_goTypes,
		DependencyIndexes: file_finality_gadget_proto_depIdxs,
		MessageInfos:      file_finality_gadget_proto_msgTypes,
	}.Build()
	File_finality_gadget_proto = out.File
	file_finality_gadget_proto_rawDesc = nil
	file_finality_gadget_proto_goTypes = nil
	file_finality_gadget_proto_depIdxs = nil
}
